/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsIndexRouteImport } from './routes/actions/index'
import { Route as AssistanceIndexRouteImport } from './routes/assistance/index'
import { Route as AssistanceCase_idRouteImport } from './routes/assistance/$case_id'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as OverviewIndexRouteImport } from './routes/overview/index'
import { Route as YardIndexRouteImport } from './routes/yard/index'
import { Route as CarsVinIndexRouteImport } from './routes/cars/$vin/index'
import { Route as CarsVinReportRouteImport } from './routes/cars/$vin/report'
import { Route as LabReleasesReleaseIdRouteImport } from './routes/lab/releases/$releaseId'
import { Route as LabScenariosScenarioIdRouteImport } from './routes/lab/scenarios/$scenarioId'
import { Route as QualityInspectionsIndexRouteImport } from './routes/quality/inspections/index'
import { Route as QualityInspectionsVinRouteImport } from './routes/quality/inspections/$vin'
import { Route as QualityReworkIndexRouteImport } from './routes/quality/rework/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsIndexRoute = ActionsIndexRouteImport.update({
  id: '/actions/',
  path: '/actions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistanceIndexRoute = AssistanceIndexRouteImport.update({
  id: '/assistance/',
  path: '/assistance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistanceCase_idRoute = AssistanceCase_idRouteImport.update({
  id: '/assistance/$case_id',
  path: '/assistance/$case_id',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const YardIndexRoute = YardIndexRouteImport.update({
  id: '/yard/',
  path: '/yard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsVinIndexRoute = CarsVinIndexRouteImport.update({
  id: '/cars/$vin/',
  path: '/cars/$vin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsVinReportRoute = CarsVinReportRouteImport.update({
  id: '/cars/$vin/report',
  path: '/cars/$vin/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LabReleasesReleaseIdRoute = LabReleasesReleaseIdRouteImport.update({
  id: '/lab/releases/$releaseId',
  path: '/lab/releases/$releaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabScenariosScenarioIdRoute = LabScenariosScenarioIdRouteImport.update({
  id: '/lab/scenarios/$scenarioId',
  path: '/lab/scenarios/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityInspectionsIndexRoute = QualityInspectionsIndexRouteImport.update({
  id: '/quality/inspections/',
  path: '/quality/inspections/',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityInspectionsVinRoute = QualityInspectionsVinRouteImport.update({
  id: '/quality/inspections/$vin',
  path: '/quality/inspections/$vin',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityReworkIndexRoute = QualityReworkIndexRouteImport.update({
  id: '/quality/rework/',
  path: '/quality/rework/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistance/$case_id': typeof AssistanceCase_idRoute
  '/actions/': typeof ActionsIndexRoute
  '/assistance/': typeof AssistanceIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/lab/': typeof LabIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/yard/': typeof YardIndexRoute
  '/cars/$vin/report': typeof CarsVinReportRoute
  '/lab/releases/$releaseId': typeof LabReleasesReleaseIdRoute
  '/lab/scenarios/$scenarioId': typeof LabScenariosScenarioIdRoute
  '/quality/inspections/$vin': typeof QualityInspectionsVinRoute
  '/cars/$vin/': typeof CarsVinIndexRoute
  '/quality/inspections/': typeof QualityInspectionsIndexRoute
  '/quality/rework/': typeof QualityReworkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistance/$case_id': typeof AssistanceCase_idRoute
  '/actions': typeof ActionsIndexRoute
  '/assistance': typeof AssistanceIndexRoute
  '/cars': typeof CarsIndexRoute
  '/lab': typeof LabIndexRoute
  '/overview': typeof OverviewIndexRoute
  '/yard': typeof YardIndexRoute
  '/cars/$vin/report': typeof CarsVinReportRoute
  '/lab/releases/$releaseId': typeof LabReleasesReleaseIdRoute
  '/lab/scenarios/$scenarioId': typeof LabScenariosScenarioIdRoute
  '/quality/inspections/$vin': typeof QualityInspectionsVinRoute
  '/cars/$vin': typeof CarsVinIndexRoute
  '/quality/inspections': typeof QualityInspectionsIndexRoute
  '/quality/rework': typeof QualityReworkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistance/$case_id': typeof AssistanceCase_idRoute
  '/actions/': typeof ActionsIndexRoute
  '/assistance/': typeof AssistanceIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/lab/': typeof LabIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/yard/': typeof YardIndexRoute
  '/cars/$vin/report': typeof CarsVinReportRoute
  '/lab/releases/$releaseId': typeof LabReleasesReleaseIdRoute
  '/lab/scenarios/$scenarioId': typeof LabScenariosScenarioIdRoute
  '/quality/inspections/$vin': typeof QualityInspectionsVinRoute
  '/cars/$vin/': typeof CarsVinIndexRoute
  '/quality/inspections/': typeof QualityInspectionsIndexRoute
  '/quality/rework/': typeof QualityReworkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistance/$case_id'
    | '/actions/'
    | '/assistance/'
    | '/cars/'
    | '/lab/'
    | '/overview/'
    | '/yard/'
    | '/cars/$vin/report'
    | '/lab/releases/$releaseId'
    | '/lab/scenarios/$scenarioId'
    | '/quality/inspections/$vin'
    | '/cars/$vin/'
    | '/quality/inspections/'
    | '/quality/rework/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistance/$case_id'
    | '/actions'
    | '/assistance'
    | '/cars'
    | '/lab'
    | '/overview'
    | '/yard'
    | '/cars/$vin/report'
    | '/lab/releases/$releaseId'
    | '/lab/scenarios/$scenarioId'
    | '/quality/inspections/$vin'
    | '/cars/$vin'
    | '/quality/inspections'
    | '/quality/rework'
  id:
    | '__root__'
    | '/'
    | '/assistance/$case_id'
    | '/actions/'
    | '/assistance/'
    | '/cars/'
    | '/lab/'
    | '/overview/'
    | '/yard/'
    | '/cars/$vin/report'
    | '/lab/releases/$releaseId'
    | '/lab/scenarios/$scenarioId'
    | '/quality/inspections/$vin'
    | '/cars/$vin/'
    | '/quality/inspections/'
    | '/quality/rework/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistanceCase_idRoute: typeof AssistanceCase_idRoute
  ActionsIndexRoute: typeof ActionsIndexRoute
  AssistanceIndexRoute: typeof AssistanceIndexRoute
  CarsIndexRoute: typeof CarsIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  OverviewIndexRoute: typeof OverviewIndexRoute
  YardIndexRoute: typeof YardIndexRoute
  CarsVinReportRoute: typeof CarsVinReportRoute
  LabReleasesReleaseIdRoute: typeof LabReleasesReleaseIdRoute
  LabScenariosScenarioIdRoute: typeof LabScenariosScenarioIdRoute
  QualityInspectionsVinRoute: typeof QualityInspectionsVinRoute
  CarsVinIndexRoute: typeof CarsVinIndexRoute
  QualityInspectionsIndexRoute: typeof QualityInspectionsIndexRoute
  QualityReworkIndexRoute: typeof QualityReworkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/': {
      id: '/actions/'
      path: '/actions'
      fullPath: '/actions/'
      preLoaderRoute: typeof ActionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistance/': {
      id: '/assistance/'
      path: '/assistance'
      fullPath: '/assistance/'
      preLoaderRoute: typeof AssistanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistance/$case_id': {
      id: '/assistance/$case_id'
      path: '/assistance/$case_id'
      fullPath: '/assistance/$case_id'
      preLoaderRoute: typeof AssistanceCase_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/': {
      id: '/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof OverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yard/': {
      id: '/yard/'
      path: '/yard'
      fullPath: '/yard/'
      preLoaderRoute: typeof YardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$vin/': {
      id: '/cars/$vin/'
      path: '/cars/$vin'
      fullPath: '/cars/$vin/'
      preLoaderRoute: typeof CarsVinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$vin/report': {
      id: '/cars/$vin/report'
      path: '/cars/$vin/report'
      fullPath: '/cars/$vin/report'
      preLoaderRoute: typeof CarsVinReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/releases/$releaseId': {
      id: '/lab/releases/$releaseId'
      path: '/lab/releases/$releaseId'
      fullPath: '/lab/releases/$releaseId'
      preLoaderRoute: typeof LabReleasesReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/scenarios/$scenarioId': {
      id: '/lab/scenarios/$scenarioId'
      path: '/lab/scenarios/$scenarioId'
      fullPath: '/lab/scenarios/$scenarioId'
      preLoaderRoute: typeof LabScenariosScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/inspections/': {
      id: '/quality/inspections/'
      path: '/quality/inspections'
      fullPath: '/quality/inspections/'
      preLoaderRoute: typeof QualityInspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/inspections/$vin': {
      id: '/quality/inspections/$vin'
      path: '/quality/inspections/$vin'
      fullPath: '/quality/inspections/$vin'
      preLoaderRoute: typeof QualityInspectionsVinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/rework/': {
      id: '/quality/rework/'
      path: '/quality/rework'
      fullPath: '/quality/rework/'
      preLoaderRoute: typeof QualityReworkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistanceCase_idRoute: AssistanceCase_idRoute,
  ActionsIndexRoute: ActionsIndexRoute,
  AssistanceIndexRoute: AssistanceIndexRoute,
  CarsIndexRoute: CarsIndexRoute,
  LabIndexRoute: LabIndexRoute,
  OverviewIndexRoute: OverviewIndexRoute,
  YardIndexRoute: YardIndexRoute,
  CarsVinReportRoute: CarsVinReportRoute,
  LabReleasesReleaseIdRoute: LabReleasesReleaseIdRoute,
  LabScenariosScenarioIdRoute: LabScenariosScenarioIdRoute,
  QualityInspectionsVinRoute: QualityInspectionsVinRoute,
  CarsVinIndexRoute: CarsVinIndexRoute,
  QualityInspectionsIndexRoute: QualityInspectionsIndexRoute,
  QualityReworkIndexRoute: QualityReworkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
